In [8]:
import numpy as np
a = np.array([1, 2, 3, 4, 5])
print(a)

[1 2 3 4 5]


In [12]:
import numpy as np
a = np.arange(1, 11)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [19]:
import numpy as np
a = np.arange(1, 22)
print(a/3)
print(a*2)


[0.33333333 0.66666667 1.         1.33333333 1.66666667 2.
 2.33333333 2.66666667 3.         3.33333333 3.66666667 4.
 4.33333333 4.66666667 5.         5.33333333 5.66666667 6.
 6.33333333 6.66666667 7.        ]
[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42]


In [20]:
import numpy as np
matrix = np.arange(1,10).reshape(3, 3)
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [24]:
import numpy as np
matrix = np.array([[22, 33, 44,],[34, 11, 56],[9, 10, 7]])
print(matrix[1, 2])
print(matrix[1, 1])
print(matrix[:, 1])



56
11
[33 11 10]


In [26]:
import numpy as np
stat = np.array([11, 33, 54, 23, 13, 55, 213])
print(np.mean(stat))
print(np.max(stat))
print(np.sum(stat))

57.42857142857143
213
402


In [38]:
import numpy as np
rand = np.random.randint(1, 324, size = 7)
print(rand)

[105 249 225 161 214 236 270]
